/* eslint-disable prettier/prettier */
const roomData= [
  {
    image: "",
    id: "1",
    room_number: 112,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 241,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 200,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Tea / Coffee Maker"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 92,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 139,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 116,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner", "Kitchen","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 176,
    room_type: 'Double bed',
    name: 'Deluxe A-91234',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 202,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 82,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: ["Air Conditioner","Swimming pool","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 23,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 88,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  },
  {
    image: "",
    id: "1",
    room_number: 148,
    room_type: 'Double bed',
    name: 'Deluxe A-91254',
    amenities: [ "Breakfast","Swimming pool","Mini Bar / Mini Fridge"],
    price: "100",
    offer_price: "90",
    status: 'Occupied',
  }
]  
module.exports = { roomData } 